// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IMultiStablecoinOracle$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IMultiStablecoinOracle";
  readonly sourceName: "contracts/DCBTreasury/v3/interfaces/IMultiStablecoinOracle.sol";
  readonly abi: [{"inputs":[{"internalType":"string[]","name":"symbols","type":"string[]"},{"internalType":"uint256[]","name":"prices","type":"uint256[]"}],"name":"batchUpdatePrices","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"getAllSymbols","outputs":[{"internalType":"string[]","name":"","type":"string[]"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getAveragePrice","outputs":[{"internalType":"uint256","name":"price","type":"uint256"},{"internalType":"uint8","name":"decimals","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"symbol","type":"string"}],"name":"getPrice","outputs":[{"internalType":"uint256","name":"price","type":"uint256"},{"internalType":"uint8","name":"decimals","type":"uint8"},{"internalType":"uint256","name":"timestamp","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"getStatistics","outputs":[{"internalType":"uint256","name":"totalFeeds","type":"uint256"},{"internalType":"uint256","name":"activeFeeds","type":"uint256"},{"internalType":"uint256","name":"totalWeight","type":"uint256"},{"internalType":"uint256","name":"averagePrice","type":"uint256"},{"internalType":"uint256","name":"healthyCount","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"symbol","type":"string"}],"name":"isStablecoinHealthy","outputs":[{"internalType":"bool","name":"isHealthy","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"string","name":"symbol","type":"string"},{"internalType":"uint256","name":"newPrice","type":"uint256"}],"name":"updatePrice","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DCBTreasury/v3/interfaces/IMultiStablecoinOracle.sol";
  readonly buildInfoId: "solc-0_8_20-a1c61539025f0654ad3a75bdb2b55239eb68e7f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IMultiStablecoinOracle"]: IMultiStablecoinOracle$Type;
    ["contracts/DCBTreasury/v3/interfaces/IMultiStablecoinOracle.sol:IMultiStablecoinOracle"]: IMultiStablecoinOracle$Type;
  }
}