/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SettlementRegistry {
  export type SettlementStruct = {
    status: BigNumberish;
    amount: BigNumberish;
    beneficiary: AddressLike;
    iso20022Hash: BytesLike;
    iso4217: BytesLike;
    timestamp: BigNumberish;
    txRef: BytesLike;
  };

  export type SettlementStructOutput = [
    status: bigint,
    amount: bigint,
    beneficiary: string,
    iso20022Hash: string,
    iso4217: string,
    timestamp: bigint,
    txRef: string
  ] & {
    status: bigint;
    amount: bigint;
    beneficiary: string;
    iso20022Hash: string;
    iso4217: string;
    timestamp: bigint;
    txRef: string;
  };
}

export interface SettlementRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "createSettlement"
      | "exists"
      | "getRoleAdmin"
      | "getSettlement"
      | "getStatus"
      | "grantRole"
      | "hasRole"
      | "renounceRole"
      | "revokeRole"
      | "setDelivered"
      | "setFailed"
      | "setMinted"
      | "settlements"
      | "supportsInterface"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SettlementCreated"
      | "StatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createSettlement",
    values: [BytesLike, BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "exists", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSettlement",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelivered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFailed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinted",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settlements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDelivered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFailed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setMinted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementCreatedEvent {
  export type InputTuple = [
    holdId: BytesLike,
    amount: BigNumberish,
    beneficiary: AddressLike,
    iso20022Hash: BytesLike,
    iso4217: BytesLike
  ];
  export type OutputTuple = [
    holdId: string,
    amount: bigint,
    beneficiary: string,
    iso20022Hash: string,
    iso4217: string
  ];
  export interface OutputObject {
    holdId: string;
    amount: bigint;
    beneficiary: string;
    iso20022Hash: string;
    iso4217: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatusUpdatedEvent {
  export type InputTuple = [
    holdId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    amount: BigNumberish,
    beneficiary: AddressLike,
    iso20022Hash: BytesLike,
    iso4217: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    holdId: string,
    oldStatus: bigint,
    newStatus: bigint,
    amount: bigint,
    beneficiary: string,
    iso20022Hash: string,
    iso4217: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    holdId: string;
    oldStatus: bigint;
    newStatus: bigint;
    amount: bigint;
    beneficiary: string;
    iso20022Hash: string;
    iso4217: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettlementRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SettlementRegistry;
  waitForDeployment(): Promise<this>;

  interface: SettlementRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  createSettlement: TypedContractMethod<
    [
      holdId: BytesLike,
      amount: BigNumberish,
      beneficiary: AddressLike,
      iso20022Hash: BytesLike,
      iso4217: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  exists: TypedContractMethod<[holdId: BytesLike], [boolean], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSettlement: TypedContractMethod<
    [holdId: BytesLike],
    [SettlementRegistry.SettlementStructOutput],
    "view"
  >;

  getStatus: TypedContractMethod<[holdId: BytesLike], [bigint], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setDelivered: TypedContractMethod<[holdId: BytesLike], [void], "nonpayable">;

  setFailed: TypedContractMethod<[holdId: BytesLike], [void], "nonpayable">;

  setMinted: TypedContractMethod<
    [holdId: BytesLike, txRef: BytesLike],
    [void],
    "nonpayable"
  >;

  settlements: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, string, string, bigint, string] & {
        status: bigint;
        amount: bigint;
        beneficiary: string;
        iso20022Hash: string;
        iso4217: string;
        timestamp: bigint;
        txRef: string;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createSettlement"
  ): TypedContractMethod<
    [
      holdId: BytesLike,
      amount: BigNumberish,
      beneficiary: AddressLike,
      iso20022Hash: BytesLike,
      iso4217: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "exists"
  ): TypedContractMethod<[holdId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSettlement"
  ): TypedContractMethod<
    [holdId: BytesLike],
    [SettlementRegistry.SettlementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStatus"
  ): TypedContractMethod<[holdId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDelivered"
  ): TypedContractMethod<[holdId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFailed"
  ): TypedContractMethod<[holdId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinted"
  ): TypedContractMethod<
    [holdId: BytesLike, txRef: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlements"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, string, string, string, bigint, string] & {
        status: bigint;
        amount: bigint;
        beneficiary: string;
        iso20022Hash: string;
        iso4217: string;
        timestamp: bigint;
        txRef: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;

  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementCreated"
  ): TypedContractEvent<
    SettlementCreatedEvent.InputTuple,
    SettlementCreatedEvent.OutputTuple,
    SettlementCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StatusUpdated"
  ): TypedContractEvent<
    StatusUpdatedEvent.InputTuple,
    StatusUpdatedEvent.OutputTuple,
    StatusUpdatedEvent.OutputObject
  >;

  filters: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SettlementCreated(bytes32,uint256,address,bytes32,bytes3)": TypedContractEvent<
      SettlementCreatedEvent.InputTuple,
      SettlementCreatedEvent.OutputTuple,
      SettlementCreatedEvent.OutputObject
    >;
    SettlementCreated: TypedContractEvent<
      SettlementCreatedEvent.InputTuple,
      SettlementCreatedEvent.OutputTuple,
      SettlementCreatedEvent.OutputObject
    >;

    "StatusUpdated(bytes32,uint8,uint8,uint256,address,bytes32,bytes3,uint256)": TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
    StatusUpdated: TypedContractEvent<
      StatusUpdatedEvent.InputTuple,
      StatusUpdatedEvent.OutputTuple,
      StatusUpdatedEvent.OutputObject
    >;
  };
}
