#!/usr/bin/env python3
"""
Generate Sample Financial Data for Audit Bank Module Testing
Creates realistic mock bank statements and financial documents
"""

import os
import json
from datetime import datetime, timedelta
import random

# Configuración
OUTPUT_DIR = "./data/Digital Commercial Bank Ltd"
SAMPLE_FILES = [
    "bank_statements/emirates_nbd_statement_2024.txt",
    "bank_statements/banco_brasil_extract_q4.txt",
    "certificates/ubs_certificate_deposit.txt",
    "instruments/barclays_repo_agreement.txt",
    "transfers/wire_transfer_log_2024.json",
    "savings/hsbc_savings_statement.txt",
    "institutional/jpmorgan_wholesale_deposit.txt",
]

# Datos de muestra
BANKS = [
    ("Emirates NBD", "EBILAEAD", "AED", "1234567890123456"),
    ("Banco do Brasil", "BRASBRRJ", "BRL", "0000443287654321"),
    ("UBS", "UBSWCHZH", "CHF", "9876543210987654"),
    ("Barclays", "BARCGB22", "GBP", "5567788990011223"),
    ("HSBC", "HSBCHKHH", "HKD", "7788990011223344"),
    ("JPMorgan", "CHASUS33", "USD", "1122334455667788"),
]

def create_directory_structure():
    """Crea la estructura de directorios"""
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    for file_path in SAMPLE_FILES:
        dir_path = os.path.join(OUTPUT_DIR, os.path.dirname(file_path))
        os.makedirs(dir_path, exist_ok=True)
    print(f"✓ Estructura de directorios creada en {OUTPUT_DIR}")

def generate_bank_statement(bank_name, swift, currency, account, amount, statement_type="checking"):
    """Genera un extracto bancario realista"""
    date = datetime.now()
    
    template = f"""
{'='*70}
                    {bank_name.upper()}
                    BANK STATEMENT
{'='*70}

Account Holder:     ACME CORPORATION LTD
Account Number:     {account}
SWIFT/BIC:          {swift}
Statement Period:   {date.strftime('%B %Y')}
Statement Date:     {date.strftime('%B %d, %Y')}

{'='*70}
ACCOUNT INFORMATION
{'='*70}

Account Type:       {statement_type.upper()} ACCOUNT
Currency:           {currency}
Branch:             International Banking Division
Status:             ACTIVE - VERIFIED

{'='*70}
BALANCE SUMMARY
{'='*70}

Opening Balance:    {currency} {amount * 0.8:,.2f}
Total Credits:      {currency} {amount * 0.3:,.2f}
Total Debits:       {currency} {amount * 0.1:,.2f}

CURRENT BALANCE:    {currency} {amount:,.2f}
                    (As of {date.strftime('%B %d, %Y')})

Available Balance:  {currency} {amount:,.2f}

{'='*70}
TRANSACTION HISTORY - LAST 30 DAYS
{'='*70}

Date         Description                    Debit          Credit        Balance
{'-'*70}
"""
    
    # Generar algunas transacciones
    running_balance = amount * 0.8
    for i in range(5):
        trans_date = date - timedelta(days=random.randint(1, 30))
        trans_type = random.choice(["Wire Transfer In", "Deposit", "Interest Credit"])
        trans_amount = amount * 0.06
        running_balance += trans_amount
        
        template += f"{trans_date.strftime('%d/%m/%Y')}   {trans_type:<30} {'':<15} {currency} {trans_amount:>12,.2f}  {currency} {running_balance:>12,.2f}\n"
    
    template += f"""
{'='*70}
IMPORTANT NOTICES
{'='*70}

This account is verified and compliant with international banking standards.
All funds are readily available for transfer via SWIFT network.

Verification Status: VERIFIED AND CERTIFIED
Compliance: ISO 20022, SWIFT MT799/MT999, FEDWIRE

For inquiries, contact: international@{bank_name.lower().replace(' ', '')}.com

{'='*70}
                    END OF STATEMENT
{'='*70}

Generated by: {bank_name} Core Banking System
Hash: {hash(date.strftime('%Y%m%d') + account) & 0xFFFFFFFF:08x}
This is an official bank document.
"""
    
    return template

def generate_certificate_deposit():
    """Genera un certificado de depósito"""
    date = datetime.now()
    maturity = date + timedelta(days=730)  # 2 años
    
    template = f"""
{'='*70}
                    UBS SWITZERLAND
              CERTIFICATE OF DEPOSIT (CD)
{'='*70}

Certificate Number:  CD-{random.randint(100000, 999999)}
Issue Date:          {date.strftime('%B %d, %Y')}
Maturity Date:       {maturity.strftime('%B %d, %Y')}

{'='*70}
DEPOSITOR INFORMATION
{'='*70}

Name:                ACME HOLDINGS INTERNATIONAL SA
Account Number:      9876543210987654
SWIFT/BIC:           UBSWCHZH80A
Tax ID:              CHE-123.456.789

{'='*70}
DEPOSIT DETAILS
{'='*70}

Principal Amount:    USD 5,000,000.00
Interest Rate:       3.50% per annum
Interest Type:       Fixed Rate
Compounding:         Semi-annually

Estimated Maturity Value: USD 5,357,500.00

{'='*70}
CLASSIFICATION
{'='*70}

Asset Type:          Large Time Deposit (M3)
Minimum Term:        24 months
Early Withdrawal:    Penalty applies
Institutional:       Yes (Principal > 1M USD)

{'='*70}
TERMS AND CONDITIONS
{'='*70}

This Certificate of Deposit is issued by UBS AG, Switzerland, and represents
a large time deposit classified as M3 (Broad Money) under monetary aggregates
standards. The deposit is insured and complies with Basel III requirements.

All funds are held in segregated accounts and are available upon maturity or
with penalties for early withdrawal as per terms.

{'='*70}
CERTIFICATION
{'='*70}

This document certifies that the above-mentioned funds are on deposit with
UBS AG and are verified as available institutional funds.

Authorized Signature: _______________________
                      Chief Financial Officer
                      UBS Institutional Banking

Date: {date.strftime('%B %d, %Y')}

{'='*70}
"""
    return template

def generate_repo_agreement():
    """Genera un acuerdo de repo (M4)"""
    date = datetime.now()
    maturity = date + timedelta(days=90)
    
    template = f"""
{'='*70}
                    BARCLAYS BANK PLC
              REPURCHASE AGREEMENT (REPO)
{'='*70}

Agreement Number:    REPO-{random.randint(1000, 9999)}-{date.year}
Trade Date:          {date.strftime('%B %d, %Y')}
Settlement Date:     {(date + timedelta(days=2)).strftime('%B %d, %Y')}
Maturity Date:       {maturity.strftime('%B %d, %Y')}

{'='*70}
PARTIES
{'='*70}

Seller (Repo Borrower):  ACME INVESTMENT MANAGEMENT LTD
Buyer (Repo Lender):     BARCLAYS CAPITAL MARKETS
Intermediary:            BARCLAYS BANK PLC

{'='*70}
TRANSACTION DETAILS
{'='*70}

Principal Amount:        USD 8,000,000.00
Repo Rate:               2.75% per annum
Term:                    90 days
Repurchase Price:        USD 8,055,000.00

Collateral Type:         US Treasury Securities
Collateral Value:        USD 8,400,000.00
Haircut:                 5.00%

{'='*70}
CLASSIFICATION
{'='*70}

Instrument Type:         Repurchase Agreement (REPO)
Asset Class:             M4 - Negotiable Money Market Instrument
Regulatory Status:       Qualified Financial Instrument
Treatment:               Secured Borrowing/Lending

{'='*70}
SETTLEMENT INSTRUCTIONS
{'='*70}

Payment:
  Bank:                  Barclays Bank PLC
  Account:               5567788990011223
  SWIFT:                 BARCGB22XXX
  Reference:             REPO-{random.randint(1000, 9999)}

Securities:
  Custodian:             Euroclear Bank
  Account:               12345/67890
  ISIN:                  US912828XXXX

{'='*70}
TERMS
{'='*70}

This Repurchase Agreement constitutes a financial instrument classified as M4
under monetary aggregates. The transaction is executed under GMRA (Global Master
Repurchase Agreement) and is subject to standard repo market conventions.

Both parties acknowledge that this is a money market instrument with negotiable
terms and represents institutional wholesale funding.

{'='*70}
AUTHORIZATION
{'='*70}

For Seller:              _______________________
                         Authorized Signatory
                         ACME Investment Management

For Buyer:               _______________________
                         Authorized Signatory
                         Barclays Capital Markets

Date: {date.strftime('%B %d, %Y')}

{'='*70}
"""
    return template

def generate_wire_transfer_log():
    """Genera un log de transferencias en JSON"""
    date = datetime.now()
    
    log_data = {
        "system": "Wire Transfer Processing System",
        "log_date": date.isoformat(),
        "total_transactions": 3,
        "total_volume_usd": 12700000,
        "transactions": [
            {
                "transaction_id": f"WT-{random.randint(100000, 999999)}",
                "timestamp": (date - timedelta(hours=5)).isoformat(),
                "from_account": "0000443287654321",
                "from_bank": "Banco do Brasil",
                "from_swift": "BRASBRRJ",
                "to_account": "1234567890123456",
                "to_bank": "Emirates NBD",
                "to_swift": "EBILAEAD",
                "amount": 3200000,
                "currency": "BRL",
                "amount_usd_equiv": 608000,
                "purpose": "Trade Settlement",
                "status": "COMPLETED",
                "classification": "M1 - Checking Account Transfer"
            },
            {
                "transaction_id": f"WT-{random.randint(100000, 999999)}",
                "timestamp": (date - timedelta(hours=3)).isoformat(),
                "from_account": "1234567890123456",
                "from_bank": "Emirates NBD",
                "from_swift": "EBILAEAD",
                "to_account": "9876543210987654",
                "to_bank": "UBS",
                "to_swift": "UBSWCHZH",
                "amount": 1500000,
                "currency": "AED",
                "amount_usd_equiv": 405000,
                "purpose": "Investment Transfer",
                "status": "COMPLETED",
                "classification": "M1 - Current Account"
            },
            {
                "transaction_id": f"WT-{random.randint(100000, 999999)}",
                "timestamp": (date - timedelta(hours=1)).isoformat(),
                "from_account": "1122334455667788",
                "from_bank": "JPMorgan Chase",
                "from_swift": "CHASUS33",
                "to_account": "5567788990011223",
                "to_bank": "Barclays",
                "to_swift": "BARCGB22",
                "amount": 8000000,
                "currency": "USD",
                "amount_usd_equiv": 8000000,
                "purpose": "Repo Settlement - REPO-4567",
                "status": "COMPLETED",
                "classification": "M4 - Financial Instrument"
            }
        ]
    }
    
    return json.dumps(log_data, indent=2)

def main():
    """Función principal"""
    print("=" * 70)
    print("   Digital Commercial Bank Ltd AUDIT BANK MODULE - SAMPLE DATA GENERATOR")
    print("=" * 70)
    print()
    
    create_directory_structure()
    
    # Generar archivos de muestra
    samples_created = 0
    
    # 1. Extracto Emirates NBD (M1)
    file_path = os.path.join(OUTPUT_DIR, SAMPLE_FILES[0])
    with open(file_path, 'w', encoding='utf-8') as f:
        content = generate_bank_statement("Emirates NBD", "EBILAEAD", "AED", "1234567890123456", 1500000, "current")
        f.write(content)
    print(f"✓ Creado: {SAMPLE_FILES[0]} (M1 - Current Account)")
    samples_created += 1
    
    # 2. Extracto Banco do Brasil (M1)
    file_path = os.path.join(OUTPUT_DIR, SAMPLE_FILES[1])
    with open(file_path, 'w', encoding='utf-8') as f:
        content = generate_bank_statement("Banco do Brasil", "BRASBRRJ", "BRL", "0000443287654321", 3200000, "checking")
        f.write(content)
    print(f"✓ Creado: {SAMPLE_FILES[1]} (M1 - Checking Account)")
    samples_created += 1
    
    # 3. Certificado UBS (M3)
    file_path = os.path.join(OUTPUT_DIR, SAMPLE_FILES[2])
    with open(file_path, 'w', encoding='utf-8') as f:
        content = generate_certificate_deposit()
        f.write(content)
    print(f"✓ Creado: {SAMPLE_FILES[2]} (M3 - Certificate of Deposit)")
    samples_created += 1
    
    # 4. Repo Barclays (M4)
    file_path = os.path.join(OUTPUT_DIR, SAMPLE_FILES[3])
    with open(file_path, 'w', encoding='utf-8') as f:
        content = generate_repo_agreement()
        f.write(content)
    print(f"✓ Creado: {SAMPLE_FILES[3]} (M4 - Repo Agreement)")
    samples_created += 1
    
    # 5. Log de transferencias JSON
    file_path = os.path.join(OUTPUT_DIR, SAMPLE_FILES[4])
    with open(file_path, 'w', encoding='utf-8') as f:
        content = generate_wire_transfer_log()
        f.write(content)
    print(f"✓ Creado: {SAMPLE_FILES[4]} (Wire Transfer Log)")
    samples_created += 1
    
    # 6. Cuenta de ahorro HSBC (M2)
    file_path = os.path.join(OUTPUT_DIR, SAMPLE_FILES[5])
    with open(file_path, 'w', encoding='utf-8') as f:
        content = generate_bank_statement("HSBC", "HSBCHKHH", "HKD", "7788990011223344", 500000, "savings")
        f.write(content)
    print(f"✓ Creado: {SAMPLE_FILES[5]} (M2 - Savings Account)")
    samples_created += 1
    
    # 7. Depósito institucional JPMorgan (M3)
    file_path = os.path.join(OUTPUT_DIR, SAMPLE_FILES[6])
    with open(file_path, 'w', encoding='utf-8') as f:
        content = generate_bank_statement("JPMorgan Chase", "CHASUS33", "USD", "1122334455667788", 12000000, "institutional wholesale")
        f.write(content)
    print(f"✓ Creado: {SAMPLE_FILES[6]} (M3 - Institutional Deposit)")
    samples_created += 1
    
    print()
    print("=" * 70)
    print(f"✅ COMPLETADO: {samples_created} archivos de muestra generados")
    print("=" * 70)
    print()
    print("Próximos pasos:")
    print("1. Ejecutar: python audit_Digital Commercial Bank Ltd_mclassify.py")
    print("2. Revisar resultados en: audit_Digital Commercial Bank Ltd_output_*.json")
    print("3. Abrir interfaz web y cargar resultados")
    print()

if __name__ == "__main__":
    main()


