// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Address$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Address";
  readonly sourceName: "contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"target","type":"address"}],"name":"AddressEmptyCode","type":"error"},{"inputs":[{"internalType":"address","name":"account","type":"address"}],"name":"AddressInsufficientBalance","type":"error"},{"inputs":[],"name":"FailedInnerCall","type":"error"}];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122018cdc847e698b4fbc60a2217fbac4c99bbbe1a1dcaf659969a682c1db0dd571264736f6c63430008140033";
  readonly deployedBytecode: "0x600080fdfea264697066735822122018cdc847e698b4fbc60a2217fbac4c99bbbe1a1dcaf659969a682c1db0dd571264736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_8_20-a1c61539025f0654ad3a75bdb2b55239eb68e7f3";
};

export interface Checkpoints$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Checkpoints";
  readonly sourceName: "contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220ab53f52e59872deee3e4b5f5bca0436de462f9e20cdb1639d477bfc5a43cc31e64736f6c63430008140033";
  readonly deployedBytecode: "0x600080fdfea2646970667358221220ab53f52e59872deee3e4b5f5bca0436de462f9e20cdb1639d477bfc5a43cc31e64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_8_20-a1c61539025f0654ad3a75bdb2b55239eb68e7f3";
};

export interface ECDSA$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ECDSA";
  readonly sourceName: "contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly abi: [{"inputs":[],"name":"ECDSAInvalidSignature","type":"error"},{"inputs":[{"internalType":"uint256","name":"length","type":"uint256"}],"name":"ECDSAInvalidSignatureLength","type":"error"},{"inputs":[{"internalType":"bytes32","name":"s","type":"bytes32"}],"name":"ECDSAInvalidSignatureS","type":"error"}];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122081c8d8906e84a61f962c3baab9f0b5515e9ae2853433d80890b0f1eedd7e190464736f6c63430008140033";
  readonly deployedBytecode: "0x600080fdfea264697066735822122081c8d8906e84a61f962c3baab9f0b5515e9ae2853433d80890b0f1eedd7e190464736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_8_20-a1c61539025f0654ad3a75bdb2b55239eb68e7f3";
};

export interface EIP712$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "EIP712";
  readonly sourceName: "contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212209c5f44f0e55327b88c363bbda103cd485818a0a5c458030c2fdd1d54192e2a4f64736f6c63430008140033";
  readonly deployedBytecode: "0x600080fdfea26469706673582212209c5f44f0e55327b88c363bbda103cd485818a0a5c458030c2fdd1d54192e2a4f64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_8_20-a1c61539025f0654ad3a75bdb2b55239eb68e7f3";
};

export interface Math$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Math";
  readonly sourceName: "contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220e12f33e0c576ead2a88a08a82b314bc77d3fc7b212644df2d78339bff329d90e64736f6c63430008140033";
  readonly deployedBytecode: "0x600080fdfea2646970667358221220e12f33e0c576ead2a88a08a82b314bc77d3fc7b212644df2d78339bff329d90e64736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_8_20-a1c61539025f0654ad3a75bdb2b55239eb68e7f3";
};

export interface SafeCast$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeCast";
  readonly sourceName: "contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly abi: [{"inputs":[{"internalType":"int256","name":"value","type":"int256"}],"name":"SafeCastOverflowedIntToUint","type":"error"},{"inputs":[{"internalType":"uint8","name":"bits","type":"uint8"},{"internalType":"uint256","name":"value","type":"uint256"}],"name":"SafeCastOverflowedUintDowncast","type":"error"},{"inputs":[{"internalType":"uint256","name":"value","type":"uint256"}],"name":"SafeCastOverflowedUintToInt","type":"error"}];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212209038c63c75e75c0e3ffa950befb07547ed1326b7e9053a201775378136a7103564736f6c63430008140033";
  readonly deployedBytecode: "0x600080fdfea26469706673582212209038c63c75e75c0e3ffa950befb07547ed1326b7e9053a201775378136a7103564736f6c63430008140033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DCBTreasury/v3/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_8_20-a1c61539025f0654ad3a75bdb2b55239eb68e7f3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Address"]: Address$Type
    ["Checkpoints"]: Checkpoints$Type
    ["ECDSA"]: ECDSA$Type
    ["EIP712"]: EIP712$Type
    ["Math"]: Math$Type
    ["SafeCast"]: SafeCast$Type;
    ["contracts/DCBTreasury/v3/libraries/SafeMath.sol:Address"]: Address$Type
    ["contracts/DCBTreasury/v3/libraries/SafeMath.sol:Checkpoints"]: Checkpoints$Type
    ["contracts/DCBTreasury/v3/libraries/SafeMath.sol:ECDSA"]: ECDSA$Type
    ["contracts/DCBTreasury/v3/libraries/SafeMath.sol:EIP712"]: EIP712$Type
    ["contracts/DCBTreasury/v3/libraries/SafeMath.sol:Math"]: Math$Type
    ["contracts/DCBTreasury/v3/libraries/SafeMath.sol:SafeCast"]: SafeCast$Type;
  }
}