// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BankRegistry"]: never
    ["CustodyVault"]: never
    ["ICustodyVault"]: never
    ["ILUSD"]: never
    ["IERC20"]: never
    ["LockBox"]: never
    ["PriceOracle"]: never
    ["AggregatorV3Interface"]: never
    ["USD"]: never
    ["IMultiStablecoinOracle"]: never;
  }
}